import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import Image from "next/image";

export default function Terms() {
  return (
    <div className="flex flex-col w-full min-h-screen text-[#291100] relative bg-[#F4F7F4]">
      {/* Background */}
      <div className="fixed inset-0 z-[-1]">
        <Image src="/breezy_bg.png" alt="Breezy Landscape" fill className="object-cover opacity-100" priority />
        <div className="absolute inset-0 bg-white/60 pointer-events-none backdrop-blur-[2px]"></div>
      </div>

      <div className="max-w-[800px] mx-auto p-10 mt-10 bg-white/80 backdrop-blur-md rounded-[32px] shadow-sm border border-white">
        <Link href="/" className="inline-flex items-center gap-2 text-[#5b872b] font-bold mb-6 hover:opacity-80">
          <ArrowLeft size={18} /> Back to App
        </Link>
        <h1 className="text-3xl font-fredoka font-bold mb-6">Terms and Conditions</h1>
        <div className="space-y-4 text-gray-700 text-sm leading-relaxed">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          <p>Please read these terms and conditions carefully before using CarbonIQ.</p>
          <h2 className="text-lg font-bold text-gray-900 mt-6">1. Acceptance of Terms</h2>
          <p>By accessing or using our application, you agree to be bound by these terms. If you disagree with any part of the terms, you may not access the service.</p>
          <h2 className="text-lg font-bold text-gray-900 mt-6">2. User Data and Emissions</h2>
          <p>CarbonIQ tracks and calculates carbon emissions based on user input and organizational data. You retain rights to your personal data, while we use aggregate data for the Vayundhra AI Strategy and national statistics models.</p>
          <h2 className="text-lg font-bold text-gray-900 mt-6">3. Usage of AI Insights</h2>
          <p>The insights generated by Vayundhra AI are advisory in nature. CarbonIQ is not liable for business decisions made based on these AI-generated strategies.</p>
        </div>
      </div>
    </div>
  );
}
